CREATE TABLE CONTACT (
    NAME TEXT PRIMARY KEY NOT NULL
);
CREATE TABLE PHONE (
    PHONE_NUMBER TEXT PRIMARY KEY NOT NULL,
    PHONE_TYPE TEXT NOT NULL,
    NAME TEXT NOT NULL,
    FOREIGN KEY(NAME) REFERENCES CONTACT(NAME)
);
CREATE TABLE FAVORITE (
    NAME TEXT NOT NULL UNIQUE,
    FOREIGN KEY(NAME) REFERENCES CONTACT(NAME)
);



-- SELECT CONTACT.name, GROUP_CONCAT(PHONE_NUMBER) phonelist,  GROUP_CONCAT(PHONE_TYPE)  typelist FROM CONTACT INNER JOIN PHONE ON CONTACT.name = PHONE.Name GROUP BY CONTACT.name;